on:
  push:
    branches:
      - master

name: "Publish references"

jobs:
  build:
    name: Publish references
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
    - uses: actions/checkout@v2

    - name: Set directories
      run: |
        echo "R_PKG_DIR=${R_HOME}/site-library" >> $GITHUB_ENV
        R --slave -e 'cat(paste0("R_CACHE_DIR=", dirname(tools::R_user_dir("asdasd", "cache")), "\n"))' >> $GITHUB_ENV

    - name: Restore the package directory
      uses: actions/cache@v2
      with:
        path: ${{ env.R_PKG_DIR }}
        key: preinstalled-packages

    - name: Restore the Hub directories
      uses: actions/cache@v2
      with:
        path: ${{ env.R_CACHE_DIR }}
        key: hub-cache2

    - name: Install dependencies
      shell: Rscript {0}
      run: BiocManager::install(c("Rcpp", "SingleR", "celldex", "AnnotationHub", "ensembldb"))

    - name: Run the formatter
      shell: Rscript {0}
      run: source("format.R")

    - name: Publish human reference datasets
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: "hs/*"
        name: hs-latest 
        tag: hs-latest
        body: "Files for various **celldex** human reference datasets."

    - name: Publish mouse reference datasets
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: "mm/*"
        name: mm-latest 
        tag: mm-latest
        body: "Files for various **celldex** mouse reference datasets."
